name: DaCe Verilator Compatibility Check
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for the trigger'
        required: true
        default: 'Check compatibility'
  schedule:
    - cron: '0 0 1 * *' # monthly
  pull_request:
    branches: [ main ] # to be reverted - just for testing the workflow
jobs:
  build:
    strategy:
      matrix:
        verilator_version: ['4.028', '4.034', '4.036', '4.100', 'master']
    runs-on: ubuntu-20.04
    steps:
      - name: trigger reason
        run: echo "Trigger Reason:" ${{ github.event.inputs.reason }}
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: install apt packages
        run: sudo apt-get update && sudo apt-get -y install git make autoconf g++ flex bison libfl2 libfl-dev
      - name: compile verilator
        run: git clone https://github.com/verilator/verilator.git && cd verilator && git fetch origin && if [ ! "${{ matrix.verilator_version }}" == "master" ]; then  git checkout v${{ matrix.verilator_version }}; fi && autoconf && ./configure && make -j2 && sudo make install
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: install python packages
        run: pip install pytest -r requirements.txt
      - name: install dace
        run: pip install .
      - run: pytest -m "verilator"
